// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarPeru.Api.Data;

#nullable disable

namespace StarPeru.Api.Migrations
{
    [DbContext(typeof(StarPeruContext))]
    [Migration("20251003223230_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarPeru.Api.Models.Administrador", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminID");

                    b.ToTable("Administradores", (string)null);

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            Apellido = "Principal",
                            Email = "admin@starperu.com",
                            Nombre = "Admin",
                            PasswordHash = "$2b$12$WPWaeP7tm1amuykoVAafq.xaAdL1lCOsdF30463ce2Hj.fa/WVVFG",
                            Rol = "Administrador"
                        });
                });

            modelBuilder.Entity("StarPeru.Api.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsientoID"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroAsiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VueloID")
                        .HasColumnType("int");

                    b.HasKey("AsientoID");

                    b.HasIndex("VueloID");

                    b.ToTable("Asientos", (string)null);
                });

            modelBuilder.Entity("StarPeru.Api.Models.Avion", b =>
                {
                    b.Property<int>("AvionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvionID"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AvionID");

                    b.ToTable("Aviones", (string)null);

                    b.HasData(
                        new
                        {
                            AvionID = 1,
                            Capacidad = 150,
                            Modelo = "Airbus A320"
                        },
                        new
                        {
                            AvionID = 2,
                            Capacidad = 180,
                            Modelo = "Boeing 737"
                        });
                });

            modelBuilder.Entity("StarPeru.Api.Models.Boleto", b =>
                {
                    b.Property<int>("BoletoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoletoID"));

                    b.Property<int>("AsientoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("PasajeroID")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VueloID")
                        .HasColumnType("int");

                    b.HasKey("BoletoID");

                    b.HasIndex("AsientoID")
                        .IsUnique();

                    b.HasIndex("PasajeroID");

                    b.HasIndex("VueloID");

                    b.ToTable("Boletos", (string)null);
                });

            modelBuilder.Entity("StarPeru.Api.Models.Ciudad", b =>
                {
                    b.Property<int>("CiudadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadID"));

                    b.Property<string>("CodigoIATA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionEstimadahoras")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CiudadID");

                    b.ToTable("Ciudades", (string)null);

                    b.HasData(
                        new
                        {
                            CiudadID = 1,
                            CodigoIATA = "LIM",
                            DuracionEstimadahoras = 0,
                            Nombre = "Lima"
                        },
                        new
                        {
                            CiudadID = 2,
                            CodigoIATA = "CUZ",
                            DuracionEstimadahoras = 1,
                            Nombre = "Cusco"
                        },
                        new
                        {
                            CiudadID = 3,
                            CodigoIATA = "AQP",
                            DuracionEstimadahoras = 1,
                            Nombre = "Arequipa"
                        },
                        new
                        {
                            CiudadID = 4,
                            CodigoIATA = "PIU",
                            DuracionEstimadahoras = 2,
                            Nombre = "Piura"
                        },
                        new
                        {
                            CiudadID = 5,
                            CodigoIATA = "IQT",
                            DuracionEstimadahoras = 2,
                            Nombre = "Iquitos"
                        });
                });

            modelBuilder.Entity("StarPeru.Api.Models.Pasajero", b =>
                {
                    b.Property<int>("PasajeroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasajeroID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PasajeroID");

                    b.ToTable("Pasajeros", (string)null);
                });

            modelBuilder.Entity("StarPeru.Api.Models.Personal", b =>
                {
                    b.Property<int>("PersonalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonalID");

                    b.ToTable("Personal", (string)null);

                    b.HasData(
                        new
                        {
                            PersonalID = 1,
                            Apellido = "Perez",
                            Nombre = "Juan",
                            Puesto = "Piloto"
                        },
                        new
                        {
                            PersonalID = 2,
                            Apellido = "Lopez",
                            Nombre = "Maria",
                            Puesto = "Copiloto"
                        },
                        new
                        {
                            PersonalID = 3,
                            Apellido = "Ramirez",
                            Nombre = "Ana",
                            Puesto = "Azafata"
                        });
                });

            modelBuilder.Entity("StarPeru.Api.Models.Vuelo", b =>
                {
                    b.Property<int>("VueloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VueloID"));

                    b.Property<int>("AvionID")
                        .HasColumnType("int");

                    b.Property<int>("DestinoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrigenID")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("VueloID");

                    b.HasIndex("AvionID");

                    b.HasIndex("DestinoID");

                    b.HasIndex("OrigenID");

                    b.ToTable("Vuelos", (string)null);
                });

            modelBuilder.Entity("StarPeru.Api.Models.VueloTripulacion", b =>
                {
                    b.Property<int>("VueloID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("PersonalID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("RolAsignado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VueloID", "PersonalID");

                    b.HasIndex("PersonalID");

                    b.ToTable("VueloTripulacion", (string)null);
                });

            modelBuilder.Entity("StarPeru.Api.Models.Asiento", b =>
                {
                    b.HasOne("StarPeru.Api.Models.Vuelo", "Vuelo")
                        .WithMany("Asientos")
                        .HasForeignKey("VueloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("StarPeru.Api.Models.Boleto", b =>
                {
                    b.HasOne("StarPeru.Api.Models.Asiento", "Asiento")
                        .WithOne("Boleto")
                        .HasForeignKey("StarPeru.Api.Models.Boleto", "AsientoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarPeru.Api.Models.Pasajero", "Pasajero")
                        .WithMany("Boletos")
                        .HasForeignKey("PasajeroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarPeru.Api.Models.Vuelo", "Vuelo")
                        .WithMany("Boletos")
                        .HasForeignKey("VueloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Pasajero");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("StarPeru.Api.Models.Vuelo", b =>
                {
                    b.HasOne("StarPeru.Api.Models.Avion", "Avion")
                        .WithMany("Vuelos")
                        .HasForeignKey("AvionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarPeru.Api.Models.Ciudad", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarPeru.Api.Models.Ciudad", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avion");

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("StarPeru.Api.Models.VueloTripulacion", b =>
                {
                    b.HasOne("StarPeru.Api.Models.Personal", "Personal")
                        .WithMany("VueloTripulacion")
                        .HasForeignKey("PersonalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarPeru.Api.Models.Vuelo", "Vuelo")
                        .WithMany("VueloTripulacion")
                        .HasForeignKey("VueloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("StarPeru.Api.Models.Asiento", b =>
                {
                    b.Navigation("Boleto")
                        .IsRequired();
                });

            modelBuilder.Entity("StarPeru.Api.Models.Avion", b =>
                {
                    b.Navigation("Vuelos");
                });

            modelBuilder.Entity("StarPeru.Api.Models.Pasajero", b =>
                {
                    b.Navigation("Boletos");
                });

            modelBuilder.Entity("StarPeru.Api.Models.Personal", b =>
                {
                    b.Navigation("VueloTripulacion");
                });

            modelBuilder.Entity("StarPeru.Api.Models.Vuelo", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Boletos");

                    b.Navigation("VueloTripulacion");
                });
#pragma warning restore 612, 618
        }
    }
}
